server:
  # 1)
  port: 8080
  error:
    # 2)
    whitelabel:
      enabled: false
  servlet:
    # 3)
    context-path: /
    # 4)
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true